services:
  postgresdb:
    image: postgres:15
    restart: unless-stopped
    container_name: postgresdb

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/formBuilder

volumes:
  pg_data:
